### PR TITLE
feat: update roadmap items

### PR DESCRIPTION
**Pull request by StyleShit**
Closes amplication/amplication#6886

### CODE REVIEW

**Review by GreenMachine01 — APPROVED** [review]
looks good

**Comment by souravjain540** [comment]
@StyleShit thanks for the PR, for the next time please ask for the issue first, get it assigned and then work on it.

can you please leave a comment in the issue so that I can assign it to you now.

**Comment by StyleShit** [comment]
@souravjain540

Oops, sorry 😅 
Done :)

**Comment by levivannoort** [comment]
@StyleShit thanks for the contribution, it should now be live on our site!

**Pull request merged**
