### PR TITLE
feat(community): add Champions program to community page

### PR DESCRIPTION
**Pull request by MichaelSolati**
I have some place holder SVGs for now. Please let me know what y'all think.

### CODE REVIEW

**Comment by MichaelSolati** [comment]
Our site doesn't have preview deploys, so here's a screenshot. Please let me know what should change. I'll have to ask Alex for SVGs later; I'm more worried about content/structure/etc...

image

**Comment by Bell-inna** [comment]
So this should come as a section at the community page. 
Right now we can insert it after or before the "Spread the word" section.
From layout perspective:

- Amplication Champions-> make sure it is the same size as the titles of the other sections (Spread the word e.g.)
- Text: minor tweak--> Our Champions program is a worldwide community of expert developers passionate about helping other developers build powerful services with Amplication.
- Icons: defiantly will have to be replaced with the abstract ones (no people) that are on brand. Alex can help. 
- 3 attributes text tweaks, also pls mind capitalization alignment
Expert developers
Understand the technologies that make building backend services easier and faster. 
Community contributors 
Make regular and impactful contributions to Amplication open-source community. 
Natural speakers
Can simplify complex technical topics so anyone can understand. 

Interested in becoming an Amplication Champion? Join our Discord community and reach out to a Champion to learn how.

**Comment by yuval-hazaz** [comment]
@Bell-inna @MichaelSolati @alexbass86, you can see the preview here
https://staging-blog.amplication.com/community

**Comment by Bell-inna** [comment]
@MichaelSolati please make sure the texts are updated as per above and we're using the proper icons (from @alexbass86). 
@yuval-hazaz the page looks good on mobile as well.

**Pull request merged**
